// /resources/js/app.js

// === Global CSS ===
import '../css/main.css';

// 1. IMPORT Alpine and the Store FIRST
import Alpine from 'alpinejs';
import collapse from '@alpinejs/collapse';
Alpine.plugin(collapse);

// 3. Set global and start
window.Alpine = Alpine;
Alpine.start();

// === Polyfills ===
import './utils/polyfills.js';

// === Global Modules ===
//import { initTooltips } from './ui/tooltip.js';
import { setupScrollToTop } from './ui/scroll-to-top.js';
import { setupSpinner } from './ui/spinner.js';
import { bindPartialLinks } from './utils/spa-router.js';
import { initDarkMode } from './utils/dark-mode.js';
import { LoginModal } from './modals/login-modal.js';
import { LogoutModal } from './modals/logout-modal.js';
import { ResetModal } from './modals/reset-modal.js';
import { initFooterLinks } from './ui/footer-links.js';
import { cleanupModals } from './utils/modal-cleanup.js';
import { AnimationEngine } from './utils/animations';
import { attachPhoneFormatter } from './utils/phone-formatter.js';
import { showToast } from './ui/toast.js';

// === Page Manifest ===
let PAGE_MANIFEST = [];

// Fired at most once per page load -- if the manifest fetch and/or a page
// script's dynamic import both fail (the same transient-network-blip
// failure mode can hit either), the tenant/landlord should only see one
// "please refresh" toast, not a stack of them.
let pageScriptFailureToastShown = false;
function warnPageScriptFailure() {
  if (pageScriptFailureToastShown) return;
  pageScriptFailureToastShown = true;
  showToast('Some page features failed to load. Please refresh the page.', 'error');
}

// === Global Modal Initializer ===
let loginModal, logoutModal, resetModal;

function initGlobalModals() {
  loginModal = new LoginModal('a[data-login-button]');
  logoutModal = new LogoutModal('a[data-logout-button]');
  resetModal = new ResetModal('[data-reset-button]');
}

/**
 * Load the page-manifest.json generated by Vite.
 *
 * A failed fetch here (transient network blip, cold static-file serve,
 * etc.) used to silently reset PAGE_MANIFEST to [] with only a
 * console.error -- since EVERY page-specific script's existence check goes
 * through this array, that single failure disables every button/interaction
 * a per-page script would have wired up, on the whole page, with nothing
 * visible to the user (this is exactly what made a tenant's "New
 * Application" button look broken with zero feedback). One retry after a
 * short delay recovers from most transient blips; if it still fails, warn
 * the user instead of failing completely silently.
 */
async function loadPageManifest() {
  const v = window.APP_CONFIG.buildVersion || '';
  const url = `${window.APP_CONFIG.assetBase}assets/js/page-manifest.json?v=${v}`;

  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const res = await fetch(url);
      PAGE_MANIFEST = res.ok ? await res.json() : [];
      return;
    } catch (err) {
      if (attempt === 2) {
        console.error('Failed to load page-manifest.json after retry:', err);
        PAGE_MANIFEST = [];
        warnPageScriptFailure();
        return;
      }
      await new Promise((resolve) => setTimeout(resolve, 400));
    }
  }
}

/**
 * Dynamically import a page script if it exists.
 * Sub-folder aware: Strips the app's base path before matching segments.
 */
async function initPageScript(urlPathname) {
  // 1. Get the base path string (e.g., "/pmb" or "https://site.com/pmb")
  let baseUrl = window.APP_CONFIG.baseUrl || '';

  // 2. Extract just the pathname if it's a full URL, otherwise use as is
  if (baseUrl.includes('://')) {
    try {
      baseUrl = new URL(baseUrl).pathname;
    } catch (e) {
      baseUrl = baseUrl.replace(/^https?:\/\/[^\/]+/, '');
    }
  }

  // Clean trailing slashes so "/pmb/" becomes "/pmb"
  const cleanBase = baseUrl.replace(/\/$/, "");

  // 3. Subtract the base from the current path
  let internalPath = urlPathname;
  if (cleanBase && urlPathname.startsWith(cleanBase)) {
    internalPath = urlPathname.substring(cleanBase.length);
  }

  // 4. Clean segments
  const segments = internalPath.split('/').filter(Boolean);

  // 5. Handle Home Page (Root of the app)
  //
  // The server can swap what's actually rendered at "/" per account type
  // without ever changing the URL (see public/index.php: a Tenant's or
  // Landlord's "/" is the Dashboard, an Inspector's is Inspection Reports)
  // -- both shapes
  // the home URL takes, a bare root locally and the live deployment's
  // literal "pmb" segment (see pmb-page.js), land here. When that's
  // happened, APP_CONFIG.rootPageScript tells us which script actually
  // matches what's on screen instead of guessing "home-page" from a URL
  // that no longer reflects the swapped content.
  const isHomeRoute = segments.length === 0 || (segments.length === 1 && segments[0] === 'pmb');
  if (isHomeRoute) {
    await loadModule(window.APP_CONFIG?.rootPageScript || 'home-page');
    return;
  }

  // 6. The Search: Check segments (reversed to find the most specific page)
  let moduleLoaded = false;
  for (const segment of [...segments].reverse()) {
    const scriptKey = `${segment}-page`;
    if (PAGE_MANIFEST.includes(scriptKey)) {
      await loadModule(scriptKey);
      moduleLoaded = true;
      break;
    }
  }

  // 7. Fallback
  if (!moduleLoaded && segments.length === 0) {
    await loadModule('home-page');
  }
}

/**
 * Helper: Reconstructs the Vite path and executes the module init.
 * Same transient-network-blip risk as loadPageManifest() above -- one retry
 * before giving up, and a user-visible warning (instead of a silent
 * console.warn only) once retries are exhausted, since this is the step
 * that actually wires up a page's buttons/interactions.
 */
async function loadModule(scriptKey) {
  // Extra safety: Don't try to load if manifest isn't an array or doesn't have the key
  if (!Array.isArray(PAGE_MANIFEST) || !PAGE_MANIFEST.includes(scriptKey)) return;

  const v = window.APP_CONFIG.buildVersion || '';
  const scriptPath = `${window.APP_CONFIG.assetBase}assets/js/${scriptKey}.min.js?v=${v}`;

  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const module = await import(/* @vite-ignore */ scriptPath);
      if (module.init) {
        module.init();
        //console.log(`✅ Feature initialized: ${scriptKey}`);
      }
      return;
    } catch (err) {
      if (attempt === 2) {
        console.error(`Could not load feature module after retry: ${scriptKey}`, err);
        warnPageScriptFailure();
        return;
      }
      await new Promise((resolve) => setTimeout(resolve, 400));
    }
  }
}

// === Define protected paths ===
// Use the paths passed from PHP
const PROTECTED_PATHS = window.APP_CONFIG.protectedPaths || [];

/**
 * Checks if page is protected and user is logged in
 * Returns true if page script should be loaded
 */
function shouldLoadPageScript(path) {
  if (PROTECTED_PATHS.includes(path) && !window.APP_CONFIG?.isLoggedIn) {
    //console.log(`ℹ️ Protected page "${path}" detected, user not logged in — skipping page script.`);
    return false;
  }
  return true;
}

// === DOMContentLoaded ===
document.addEventListener('DOMContentLoaded', async () => {
  // Initialize global UI
  setupSpinner();
  setupScrollToTop();
  bindPartialLinks();
  initDarkMode();
  initFooterLinks();
  attachPhoneFormatter();

  // AOS must be initialized here rather than left to individual page scripts —
  // its stylesheet is loaded globally (hides every [data-aos] element until
  // JS marks it animated), so any page whose own script forgets to call this
  // would have permanently-invisible [data-aos] content (e.g. breadcrumbs) on
  // a direct/full load.
  AnimationEngine.refresh();

  // Initialize modals
  initGlobalModals();

  // PRECISION TRIGGER: Check for login request
  const urlParams = new URLSearchParams(window.location.search);
  if (urlParams.has('login')) {
    // Give the UI a tiny heartbeat to settle, then pop the modal
    setTimeout(() => {
      // Check if LoginModal class has a show/open method
      // Usually, you can trigger the click on the data-login-button 
      // or call the method directly if you stored the instance
      const loginBtn = document.querySelector('a[data-login-button]');
      if (loginBtn) loginBtn.click();
    }, 500);

    // Clean the URL so refreshing doesn't keep popping the modal
    window.history.replaceState({}, document.title, window.location.pathname);
  }

  // 🔑 Load manifest first
  await loadPageManifest();

  // 🔑 PRECISION FIX: Strip query strings and hashes for the router
  const cleanPath = window.location.pathname.replace(/\/$/, '');

  // 🔒 Only load page-specific script if allowed
  if (shouldLoadPageScript(window.location.pathname)) {
    await initPageScript(window.location.pathname);
  }
});

// === SPA partial-load event ===
// Triggered by spa-router.js after partial page replacement.
// Ensures per-page scripts and modals reinitialize correctly
// once the new DOM content is fully rendered.
document.body.addEventListener('partial-load', (e) => {
  const url = e.detail?.url || '';

  try {
    const parsedUrl = new URL(url, window.location.origin);

    // 🔑 PRECISION FIX: Use parsedUrl.pathname to ignore ?token=...
    const cleanPath = parsedUrl.pathname.replace(/\/$/, '');

    // 🔒 Skip page script initialization for protected pages if not logged in
    if (!shouldLoadPageScript(parsedUrl.pathname)) return;

    // 🕒 Wait briefly to ensure #main-content's new HTML is fully parsed & attached
    // This prevents "missing DOM elements" issues in modules like messages-page.js
    setTimeout(async () => {
      try {
        cleanupModals();            // 🧹 Remove old modals & MutationObservers
        AnimationEngine.refresh();  // 🎬 Reveal [data-aos] content swapped into #main-content
        await initPageScript(parsedUrl.pathname); // 🚀 Load & init the new page script
        initGlobalModals();         // 🔁 Rebind login/logout/reset modals
      } catch (err) {
        console.error('Failed to initialize page script after partial load:', err);
      }
    }, 25); // ← Small delay ensures DOM is ready (25ms is enough)

  } catch (err) {
    console.error('Failed to parse SPA partial URL for page script:', err);
  }
});
